# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: noop
        name: No-op Hook
        entry: echo "This is a dummy pre-commit hook that does nothing."
        language: system
        stages: [commit]
